.PHONY: clean

pointerqueue:
	@chmod 755 .
	@python2 pointerqueue.py

loctree:
	@chmod 755 .
	@python2 loctree.py

lcrstree:
	@chmod 755 .
	@python2 lcrstree.py

mergelists:
	@chmod 755 .
	@python2 mergelists.py

listconcat:
	@chmod 755 .
	@python2 listconcat.py

levelorder:
	@chmod 755 .
	@python2 levelorder.py

preorder:
	@chmod 755 .
	@python2 preorder.py

postorder:
	@chmod 755 .
	@python2 postorder.py

huffman:
	@chmod 755 .
	@python3 huffman.py
